# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Desktop\CDOFHI\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1600, 1200)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 1200))
        MainWindow.setMaximumSize(QtCore.QSize(1600, 1200))
        MainWindow.setStyleSheet("background-color: rgb(104, 104, 104);\n"
"\n"
"color：white；")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:rgb(69, 94, 255);\n"
"border-bottom-right-radius:10px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"color：white；")
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1060, 820, 411, 191))
        font = QtGui.QFont()
        font.setFamily("仿宋_GB2312")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"background-color: rgb(35, 94, 255);\n"
"font: 20pt \"仿宋_GB2312\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 840, 181, 71))
        font = QtGui.QFont()
        font.setFamily("仿宋_GB2312")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"font: 20pt \"仿宋_GB2312\";\n"
"background-color:rgb(30, 32, 161);")
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(350, 820, 391, 91))
        self.textEdit.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 920, 181, 81))
        font = QtGui.QFont()
        font.setFamily("仿宋_GB2312")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"font: 20pt \"仿宋_GB2312\";\n"
"background-color:rgb(30, 32, 161);")
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(350, 917, 391, 91))
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 287, 640, 480))
        self.label.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(620, 170, 421, 61))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px;\n"
"\n"
"    font: 16pt \"华文琥珀\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 1040, 151, 81))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px;\n"
"\n"
"    font: 16pt \"华文琥珀\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 1040, 231, 81))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px;\n"
"\n"
"    font: 16pt \"华文琥珀\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(860, 290, 640, 480))
        self.label_5.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.textEdit.raise_()
        self.label_4.raise_()
        self.textEdit_2.raise_()
        self.label.raise_()
        self.pushButton_3.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "  用户登录界面"))
        self.label_3.setText(_translate("MainWindow", "用户名："))
        self.label_4.setText(_translate("MainWindow", "密码："))
        self.pushButton_3.setText(_translate("MainWindow", "打开摄像头"))
        self.pushButton_2.setText(_translate("MainWindow", "登录"))
        self.pushButton.setText(_translate("MainWindow", "注册账号"))
import pictures_rc
