# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Desktop\CDOFHI\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_2(object):
    def setupUi(self, register_2):
        register_2.setObjectName("register_2")
        register_2.resize(1600, 1200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(register_2.sizePolicy().hasHeightForWidth())
        register_2.setSizePolicy(sizePolicy)
        register_2.setMinimumSize(QtCore.QSize(1600, 1200))
        register_2.setMaximumSize(QtCore.QSize(1600, 1200))
        register_2.setStyleSheet("background-color: rgb(104, 104, 104);\n"
"border-bottom-right-radius:10px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"color：white；")
        self.centralwidget = QtWidgets.QWidget(register_2)
        self.centralwidget.setMinimumSize(QtCore.QSize(1600, 1200))
        self.centralwidget.setMaximumSize(QtCore.QSize(1600, 1200))
        self.centralwidget.setStyleSheet("background-color:rgb(69, 94, 255);\n"
"border-bottom-right-radius:10px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"color：white；")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(440, 520, 261, 101))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px;\n"
"\n"
"    font: 16pt \"华文琥珀\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 430, 151, 41))
        self.label_3.setStyleSheet("font: 16pt \"仿宋_GB2312\";\n"
"\n"
"color:white")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 510, 161, 51))
        self.label_7.setStyleSheet("font: 16pt \"仿宋_GB2312\";\n"
"\n"
"color:white")
        self.label_7.setObjectName("label_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 1100, 141, 71))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-color:rgb(97, 65, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color:white\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color:rgb(134, 134, 134);\n"
"}\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 330, 161, 41))
        self.label_2.setStyleSheet("font: 16pt \"仿宋_GB2312\";\n"
"\n"
"color:white")
        self.label_2.setObjectName("label_2")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(50, 499, 301, 81))
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(460, 1100, 131, 71))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-color:rgb(154, 47, 20);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color:white\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color:rgb(134, 134, 134);\n"
"}\n"
"\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(440, 410, 261, 101))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px;\n"
"\n"
"    font: 16pt \"华文琥珀\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setGeometry(QtCore.QRect(50, 240, 301, 71))
        self.lcdNumber_7.setStyleSheet("boder:none")
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(80, 590, 251, 41))
        self.checkBox_2.setStyleSheet("font: 16pt \"仿宋_GB2312\";\n"
"\n"
"color:white")
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(440, 300, 261, 101))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px;\n"
"\n"
"    font: 16pt \"华文琥珀\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_8.setGeometry(QtCore.QRect(40, 409, 311, 81))
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 250, 171, 51))
        self.label_8.setStyleSheet("font: 16pt \"仿宋_GB2312\";\n"
"\n"
"color:white")
        self.label_8.setObjectName("label_8")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_9.setGeometry(QtCore.QRect(40, 320, 311, 81))
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(325, 1010, 131, 51))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(140, 1010, 141, 51))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(500, 1010, 141, 51))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(440, 230, 251, 51))
        self.textBrowser_3.setStyleSheet("background-color: rgb(182, 182, 182);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(810, 80, 640, 480))
        self.label.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(810, 640, 640, 480))
        self.label_4.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 650, 521, 440))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("仿宋_GB2312")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("font: 16pt \"仿宋_GB2312\";\n"
"\n"
"color:white")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("仿宋_GB2312")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font: 16pt \"仿宋_GB2312\";\n"
"\n"
"color:white")
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_2.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textBrowser_2)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("仿宋_GB2312")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font: 16pt \"仿宋_GB2312\";\n"
"\n"
"color:white")
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_4.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textBrowser_4)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textBrowser)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1600, 1200))
        self.label_5.setMinimumSize(QtCore.QSize(1600, 1200))
        self.label_5.setMaximumSize(QtCore.QSize(1600, 1200))
        self.label_5.setStyleSheet("background-image: url(:/media/1.jpg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.pushButton_15.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.lcdNumber_9.raise_()
        self.lcdNumber_6.raise_()
        self.lcdNumber_8.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.lcdNumber_7.raise_()
        self.checkBox_2.raise_()
        self.pushButton_12.raise_()
        self.label_8.raise_()
        self.layoutWidget.raise_()
        self.textBrowser_3.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_7.raise_()
        register_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(register_2)
        QtCore.QMetaObject.connectSlotsByName(register_2)

    def retranslateUi(self, register_2):
        _translate = QtCore.QCoreApplication.translate
        register_2.setWindowTitle(_translate("register_2", "MainWindow"))
        self.pushButton_8.setText(_translate("register_2", "开启语音控制"))
        self.label_3.setText(_translate("register_2", "Y轴速度"))
        self.label_7.setText(_translate("register_2", "Z轴速度"))
        self.pushButton_9.setText(_translate("register_2", "起飞"))
        self.label_2.setText(_translate("register_2", "X轴速度"))
        self.pushButton_10.setText(_translate("register_2", "退出程序"))
        self.pushButton_11.setText(_translate("register_2", "开启手势控制"))
        self.checkBox_2.setText(_translate("register_2", "无人机连接"))
        self.pushButton_12.setText(_translate("register_2", "开启键盘控制"))
        self.label_8.setText(_translate("register_2", "  电量"))
        self.pushButton_15.setText(_translate("register_2", "开启车牌识别"))
        self.pushButton_13.setText(_translate("register_2", "开启行人识别"))
        self.pushButton_14.setText(_translate("register_2", "开启三维重建"))
        self.label.setText(_translate("register_2", " 地面端"))
        self.label_4.setText(_translate("register_2", "无人机端"))
        self.label_11.setText(_translate("register_2", "键盘控制信号："))
        self.label_12.setText(_translate("register_2", "语音控制信号："))
        self.label_13.setText(_translate("register_2", "手势控制信号"))
        self.textBrowser_4.setHtml(_translate("register_2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import pictures_rc
