# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Desktop\CDOFHI\register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_3(object):
    def setupUi(self, register_3):
        register_3.setObjectName("register_3")
        register_3.resize(1600, 1200)
        register_3.setMinimumSize(QtCore.QSize(1600, 1200))
        register_3.setMaximumSize(QtCore.QSize(1600, 1200))
        register_3.setStyleSheet("background-color: rgb(104, 104, 104);\n"
"\n"
"color：white；")
        self.centralwidget = QtWidgets.QWidget(register_3)
        self.centralwidget.setStyleSheet("background-color:rgb(69, 94, 255);\n"
"border-bottom-right-radius:10px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"color：white；")
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(350, 917, 391, 91))
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 837, 111, 71))
        font = QtGui.QFont()
        font.setFamily("仿宋_GB2312")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"font: 20pt \"仿宋_GB2312\";\n"
"background-color:rgb(30, 32, 161);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 917, 111, 61))
        font = QtGui.QFont()
        font.setFamily("仿宋_GB2312")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"font: 20pt \"仿宋_GB2312\";\n"
"background-color:rgb(30, 32, 161);")
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(350, 820, 391, 91))
        self.textEdit.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1040, 830, 361, 191))
        font = QtGui.QFont()
        font.setFamily("仿宋_GB2312")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"background-color: rgb(35, 94, 255);\n"
"font: 20pt \"仿宋_GB2312\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 1050, 231, 81))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px;\n"
"\n"
"    font: 16pt \"华文琥珀\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 120, 351, 121))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px;\n"
"\n"
"    font: 16pt \"华文琥珀\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);}\n"
"QPushButton::pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px}\n"
"\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 287, 640, 480))
        self.label.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(900, 290, 640, 480))
        self.label_5.setStyleSheet("background-color: rgb(255, 244, 245);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        register_3.setCentralWidget(self.centralwidget)

        self.retranslateUi(register_3)
        QtCore.QMetaObject.connectSlotsByName(register_3)

    def retranslateUi(self, register_3):
        _translate = QtCore.QCoreApplication.translate
        register_3.setWindowTitle(_translate("register_3", "MainWindow"))
        self.label_3.setText(_translate("register_3", "用户名："))
        self.label_4.setText(_translate("register_3", "密码："))
        self.label_2.setText(_translate("register_3", "用户注册界面"))
        self.pushButton.setText(_translate("register_3", "注册账号"))
        self.pushButton_3.setText(_translate("register_3", "打开摄像头"))
import pictures_rc
